---
# tasks file for wordpress
- name: Download WordPress
  get_url:
          url=https://wordpress.org/latest.tar.gz
          dest=/tmp/wordpress.tar.gz
          validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Move wordpress content in the right directory
  shell: mv /var/www/wordpress/* /var/www/wordpress_test/

- name: remove old directory
  shell: rm -fr /var/www/wordpress

- name: install dos2unix
  apt: 
   name: dos2unix
   state: present

- name: Copy sample config file
  command: mv /var/www/wordpress_test/wp-config-sample.php /var/www/wordpress_test/wp-config.php creates=/var/www/wordpress_test/wp-config.php

- name: Update WordPress config file
  shell: sed -i 's/database_name_here/wordpress/g' /var/www/wordpress_test/wp-config.php 
- name: Update WordPress config file
  shell: sed -i 's/username_here/wordpress/g' /var/www/wordpress_test/wp-config.php
- name: Update WordPress config file  
  shell: sed -i 's/password_here/wordpress/g' /var/www/wordpress_test/wp-config.php
- name: Update WordPress config file
  shell: sed -i 's/localhost/10.159.80.119:3306/g' /var/www/wordpress_test/wp-config.php

- name: set owner
  shell: chown -R apache:apache /var/www/wordpress_test

- name: set permissions
  shell: chmod 755 /var/www/ -R  

- name: adapt files
  shell: dos2unix /var/www/wordpress_test  
  
- name: restart apache2
  service: name=apache2 state=restarted          
